version: 2.1

jobs:
  build-medium:
    machine:
      image: ubuntu-2004:current
    resource_class: arm.medium
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies
      - run: sudo apt-get update
      - run: sudo apt-get install -y build-essential libtool libelf-dev libusb-dev libhidapi-dev libftdi1-dev
      - run: ls -l
      - run: ./bootstrap
      - run: ./configure --enable-linuxspi
      - run: make	        
      - run: echo "Hello, Arm!"

workflows:
  build:
    jobs:
      - build-medium
