#
# build.yml - GitHub build action for AVRDUDE
# Copyright (C) 2021 Marius Greuel
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

name: Build

on:
  push:
  pull_request:
  workflow_call:

env:
  BUILD_TYPE: RelWithDebInfo

jobs:
  linux:
    runs-on: ubuntu-latest
    container: debian:bullseye
    strategy:
      matrix:
        include:
          - { arch: armhf, processor: armhf, prefix: arm-linux-gnueabihf, inc-lib: arm-linux-gnueabihf }
    steps:
      - uses: actions/checkout@v2
      - name: Add architecture
        run: |
          dpkg --add-architecture ${{matrix.arch}}
          apt-get update
      - name: Install prerequisites
        run: >-
          apt-get install -y
          git
          cmake
          flex
          bison
          crossbuild-essential-${{matrix.arch}}
          libelf-dev:${{matrix.arch}}
          libusb-dev:${{matrix.arch}}
          libusb-1.0-0-dev:${{matrix.arch}}
          libhidapi-dev:${{matrix.arch}}
          libftdi1-dev:${{matrix.arch}}
      - name: Build
        run: ./build.sh
      - name: Archive build artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: build-linux-${{matrix.processor}}
          path: |
            build_linux/
            !**/*.d
            !**/*.o
      - name: Archive executables
        uses: actions/upload-artifact@v2
        with:
          name: avrdude-linux-${{matrix.processor}}
          path: |
            build_linux/src/avrdude
            build_linux/src/avrdude.conf
